name: 🔗 Check Markdown Links

on: [push, pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes' # show only errors
          use-verbose-mode: 'yes' # show detailed HTTP status
          # check-modified-files-only: 'yes'
          config-file: '.github/workflows/config/mlc_config.json'

# known issues: https://developer.android.com
# https://github.com/tcort/link-check/issues/46
# https://github.com/tcort/markdown-link-check/issues/159