name: 🧼 Check Markdown Markup

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  markdown-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@9fc95163471d6460c35cccad13645912aaa25d5f
        with:
          files: Document
          config_file: ".markdownlint.json"
          ignore_files: "Tools, node_modules, Crackmes, Samples"
